# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 079ea1cedc4598c8fe6168790d0a2ef9cd470ff430d23f7b1c68eda8041d4f29e851e5a6b183fefbb7397425831ccc20ae75fe3b5a6e5a222de75d624ca637f9

test:
  secret_key_base: 3b24e9c6d12664f3f44f6870ed490df1360cd495cf093ef382ef9a8161ba7cf154a9870e01918f2861c3e2276688edb454dd8feb157d9c214bff347119f1db49

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
